---
ID: "1d5d14db-1f14-455a-bcac-9d6611011643"
Parent: "1747ff20-72e9-4dd7-9e75-5562b8f13227"
Template: "1747ff20-72e9-4dd7-9e75-5562b8f13227"
Path: /sitecore/templates/Feature/EnterpriseWeb/AndersenWindows/Components/General/Content Block With Sidebar/Content Block With Sidebar/__Standard Values
SharedFields:
- ID: "b03569b1-1534-43f2-8c83-bd064b7d782c"
  Hint: __Renderers
  Value: "{B3B40BBF-63B4-4CBB-9237-4772724213FC}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230428T182912Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a2493bc2-5011-4374-9753-cdd2e392e59f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230428T183226Z
