---
ID: "a2b0e19d-0f52-4545-9b22-8b05a65e870b"
Parent: "a90f837f-cac5-4b90-9bd0-bb062974b49d"
Template: "a90f837f-cac5-4b90-9bd0-bb062974b49d"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Components/Hero/Hero With Navigation/Hero With Navigation Link/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230223T211643Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a5237f74-9b75-45c1-885e-35579806784a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230223T211643Z
