---
ID: "beebc39c-d07c-4e00-a00c-e05c4aba431c"
Parent: "f6c078f8-f5ce-417d-bea4-e98ed089df64"
Template: "d2923fee-da4e-49be-830c-e27764dfa269"
Path: /sitecore/content/AndersenCorporation/AndersenWindows/StormDoors/Presentation/Styles/Theme/Default
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 0
- ID: "f917c951-1f75-4d62-b14a-bc6888d7eeca"
  Hint: Value
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221115T094436Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9daac0df-7e05-4b9c-8786-b809e056e761"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221219T090631Z
