---
ID: "e735d8d3-9a17-40ba-9022-7aa4f75c2fdf"
Parent: "863dcc2e-cca5-4236-b10f-8b4872e1c47c"
Template: "863dcc2e-cca5-4236-b10f-8b4872e1c47c"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Elements/Swatches/Swatch/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221108T214933Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a592be24-0abd-42db-9d83-c8e20e28b790"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d1d57e33-9333-4dd8-95c7-f2ecaaebfc4d"
      Hint: swatchName
      Value: $name
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221108T215116Z
