---
ID: "a5c9c7df-8d59-4997-b2a1-a91d1dca0077"
Parent: "246db8c1-1c1c-45c1-af6c-79733ff73baa"
Template: "246db8c1-1c1c-45c1-af6c-79733ff73baa"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Forms/Fields/Checkbox Group/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{4AAA5F48-2F4B-42E2-89CC-A4A92896D011}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230216T192449Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4eed5431-92a9-4085-86b3-83faadd80e70"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230822T044040Z
