---
ID: "35447319-bb3b-4df4-a577-263e4e485953"
Parent: "19dadbba-95ac-4f1e-867a-c64d778b90c6"
Template: "19dadbba-95ac-4f1e-867a-c64d778b90c6"
Path: /sitecore/templates/Feature/EnterpriseWeb/AndersenWindows/Components/General/Generic Chart/GenericChartColumn/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231212T160931Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jhuynh
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jhuynh
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bcd21905-0c4e-4556-916c-b4187ef66c09"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jhuynh
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231212T173320Z
