---
ID: "21433f67-57f1-4c51-ab08-266af03bacf7"
Parent: "0a3f014a-f0ae-48d9-ac2e-5c78fa7d034c"
Template: "0a3f014a-f0ae-48d9-ac2e-5c78fa7d034c"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Elements/Social/Social Link/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230625T172602Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1273a9f9-6e74-407d-8c01-02e365ce392d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230625T172602Z
