---
ID: "2517d0ec-bad7-4049-ad13-9dba709cad5e"
Parent: "8ae5a435-b529-4d6e-8f7c-5e12e5cd84b3"
Template: "8ae5a435-b529-4d6e-8f7c-5e12e5cd84b3"
Path: /sitecore/templates/Project/AndersenCorporation/RenewalByAndersen/Common/Headless Tenant/__Standard Values
SharedFields:
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: |
    ar|sitecore\RbA Author|pe|+item:rename|+item:write|+item:create|pd|+item:rename|+item:write|+item:create|ar|sitecore\RbA Admin|pe|+item:delete|+item:admin|pd|+item:delete|+item:admin|
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221018T193713Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8fbeb5ef-6657-4cf7-96e3-67f5cee8c4da"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230206T195520Z
