---
ID: "61c48a9e-1fe3-4f7e-bfb7-bbcc47b48a01"
Parent: "8cb11cd1-c5f4-4a2b-8962-495809c7741d"
Template: "8cb11cd1-c5f4-4a2b-8962-495809c7741d"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Components/Search/Search/__Standard Values
SharedFields:
- ID: "b03569b1-1534-43f2-8c83-bd064b7d782c"
  Hint: __Renderers
  Value: "{070ABA1D-97CC-4070-83CB-C7AFD9BD07C3}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 700
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230406T112205Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d6d3bc67-856b-4872-a353-8efbbb29a90d"
    - ID: "b2a74f5b-05db-4e79-8ce9-328512c478cf"
      Hint: headlineText
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231229T113435Z
