---
ID: "bb362caf-1897-475b-8ddd-f6167bb51e20"
Parent: "ae12c5f7-adad-437a-bba0-4c42be27077a"
Template: "ae12c5f7-adad-437a-bba0-4c42be27077a"
Path: /sitecore/templates/Project/AndersenCorporation/AndersenWindows/Common/JSS Site Grouping/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{E46F3AF2-39FA-4866-A157-7017C4B2A40C}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221129T230341Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "aea5bb1c-5748-410b-a3eb-27b0ddd5b347"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221130T035652Z
