---
ID: "c009f77a-69a8-444b-aeec-70f4d9f17b0d"
Parent: "e173a5bc-acd6-47c3-abf2-f0d8c41035de"
Template: "e173a5bc-acd6-47c3-abf2-f0d8c41035de"
Path: /sitecore/templates/Project/AndersenCorporation/RenewalByAndersen/Common/Page Designs/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {33C8B04D-1631-4139-8FFE-F8C44E26C969}
    {B63096E5-D215-4F66-A8AD-CC6A3FE7C63D}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221018T193713Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3274efc7-2594-4cfb-b769-6cd2a76a6a55"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221129T233744Z
