---
ID: "6a0662b4-a43f-4586-b4db-ed3c27cf96d3"
Parent: "d9fc656a-c3f3-4ec4-8e35-81fa7390018c"
Template: "d9fc656a-c3f3-4ec4-8e35-81fa7390018c"
Path: /sitecore/templates/Feature/EnterpriseWeb/RenewalByAndersen/Components/Hero/Hero Offer/Hero Offer/__Standard Values
SharedFields:
- ID: "b03569b1-1534-43f2-8c83-bd064b7d782c"
  Hint: __Renderers
  Value: "{38836F8C-2EE0-4AB9-B599-5DCA56021558}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230720T094333Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b6f6ea33-02e9-4d6d-b128-8ca460eebb58"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231220T060455Z
