---
ID: "b2b8779c-aca4-43fe-9ee4-17b63122e50c"
Parent: "0a7275dc-16ac-491d-a3d2-08c83231c8c8"
Template: "0a7275dc-16ac-491d-a3d2-08c83231c8c8"
Path: /sitecore/templates/Foundation/EnterpriseWeb/AndersenWindows/FieldSets/Navigation/_Nav Display Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230330T194652Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d76ab6a4-8f32-44a6-a12a-3cba1fa3345b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "c556ef2f-5800-4a23-9816-d9b296f479a9"
      Hint: displayType
      Value: "{F711C660-ECF3-4E50-91E0-34E899D9B8B7}"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230330T194657Z
