---
ID: "5f020e3f-3529-4fba-ac7f-abef4de3d5a7"
Parent: "312d260c-1e0d-4a1b-b73d-cc2d9fcf7632"
Template: "312d260c-1e0d-4a1b-b73d-cc2d9fcf7632"
Path: /sitecore/templates/Feature/EnterpriseWeb/AndersenWindows/Components/General/Bazaarvoice Reviews/Bazaarvoice Reviews/__Standard Values
SharedFields:
- ID: "b03569b1-1534-43f2-8c83-bd064b7d782c"
  Hint: __Renderers
  Value: "{373827C9-0FC7-4F8B-AD44-0A8792E80C59}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230330T213616Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bffe015a-f50c-4684-b963-f0597534b601"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230330T214837Z
