---
ID: "4b2a3f13-5bce-484f-900a-883fa57e57a2"
Parent: "7dcf5d52-57c1-49b3-b452-f27f980d51e3"
Template: "7dcf5d52-57c1-49b3-b452-f27f980d51e3"
Path: /sitecore/templates/Foundation/EnterpriseWeb/Enterprise/Enhanced Insert Options/Insert Options Settings/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {FF220B80-51D7-439E-B74E-7BB1DECB3272}
    {D70D43E4-AEF9-43BF-89E5-B49F22675F43}
- ID: "a0cb3965-8884-4c7a-8815-b6b2e5ced162"
  Hint: __Editors
  Value: "{A0C460F4-DBAE-4A5A-8F3A-C4ADFCDACEEA}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221130T135037Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d8fe2277-05c3-458c-a2cc-cc145feacfae"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221130T231240Z
