---
ID: "e5b77946-b12e-490f-b0c5-a9a7b5076168"
Parent: "a738d85d-53f1-4aed-a9bd-fea93ed9eccd"
Template: "a738d85d-53f1-4aed-a9bd-fea93ed9eccd"
Path: /sitecore/templates/Feature/EnterpriseWeb/AndersenWindows/Components/Tool/ESeries Sizing Calculator/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/calculator.png
- ID: "b03569b1-1534-43f2-8c83-bd064b7d782c"
  Hint: __Renderers
  Value: "{CB20A467-8FC7-4DF4-B6B3-1F05AE3FA387}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230417T171953Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "806cab60-d21f-4c19-aa49-42fcc5974ea8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230418T163059Z
