---
ID: "33a30a92-c424-4f9f-bb01-c0630f2b51c0"
Parent: "dd0c4303-275b-43a8-9b59-7f40daa9a9c4"
Template: "dd0c4303-275b-43a8-9b59-7f40daa9a9c4"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Components/Promo/Promo Image Grid/Promo Image Grid Image/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Multimedia/32x32/image.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230314T192752Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f3102b06-48eb-4b40-bf73-db8541c76e15"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230314T192913Z
