---
ID: "36d0174d-0939-40bf-b2b6-8bd521d7edf2"
Parent: "c5db4ef7-746f-44c1-a564-55a405df748e"
Template: "c5db4ef7-746f-44c1-a564-55a405df748e"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Forms/Fields/Phone/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230216T192449Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bd1cc796-82ea-4c26-903f-2e36ed07085d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d75d14d3-1a4e-47f1-a2d4-496cc1d09c0c"
      Hint: label
      Value: $name
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230813T080449Z
