---
ID: "31cd9959-79c1-4035-bb6c-cfd840b3e7bf"
Parent: "37fa519e-15f3-40e2-8212-56cf5007f97d"
Template: "37fa519e-15f3-40e2-8212-56cf5007f97d"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Elements/Search/Pager/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "08b3c477-30fd-4f4d-8e6d-a0dd454dad23"
      Hint: numberOfPages
      Value: 10
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230208T125125Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1ea4fd7c-fd6c-4362-b760-8c6529f49ea4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230215T084429Z
