---
ID: "aaf12621-40f2-46da-84e0-fa460a1accb6"
Parent: "1adbc0a2-a0a9-4341-b752-6b91f903e9b0"
Template: "1adbc0a2-a0a9-4341-b752-6b91f903e9b0"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Forms/Fields/Date/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230216T192449Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "150784fb-e2bc-4645-b73a-f6cd4e8993eb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d75d14d3-1a4e-47f1-a2d4-496cc1d09c0c"
      Hint: label
      Value: $name
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230815T134728Z
