---
ID: "10ebb00f-190b-4c8c-87b8-31742dff6d14"
Parent: "b7a62de5-84e9-48e8-8170-6b68c345c1ca"
Template: "b7a62de5-84e9-48e8-8170-6b68c345c1ca"
Path: /sitecore/templates/Project/AndersenCorporation/AndersenWindows/Pages/Custom Error Page/__Standard Values
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{DD2C902A-D7D2-4DB9-8538-C7748DAB080D}" />
    </r>
Languages:
- Language: en
  Fields:
  - ID: "9541e67d-ce8c-4225-803d-33f7f29f09ef"
    Hint: __Short description
    Value: |
      Note: Custom Error Pages must be named either "_404" or "_500" and live directly under Home.
  Versions:
  - Version: 1
    Fields:
    - ID: "2399a54b-f040-4ef6-bc16-18b144dea056"
      Hint: excludeFromSearch
      Value: 1
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221018T193700Z
    - ID: "2de2044f-fd01-4455-a82f-267986eda60b"
      Hint: excludeFromSitemap
      Value: 1
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b94dfecb-ddea-4e59-9cec-25a77c60d6f3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230907T072535Z
