---
ID: "5370c495-3da7-416a-922f-1cb7cb8c731b"
Parent: "b1feb0dc-74e8-4134-9b39-4d156b04448b"
Template: "b1feb0dc-74e8-4134-9b39-4d156b04448b"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Forms/Value Providers/Query String Value Provider/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230921T101113Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2c726ca2-2eaa-4a23-83d4-655fd8a3362c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230921T172109Z
