---
ID: "04eb2667-6903-407a-a097-24ecf00f16cf"
Parent: "57330b4d-64ac-4dad-9f5a-6776cf1be815"
Template: "57330b4d-64ac-4dad-9f5a-6776cf1be815"
Path: /sitecore/templates/Feature/EnterpriseWeb/AndersenWindows/Components/Tool/Storm Door Choose Tool/Recommendation/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161205T142904Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dsasik
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "89f80645-2f11-471d-8417-23dfc7db2d55"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dboeser
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230512T170443Z
