---
ID: "e665a0cd-7381-4464-87a2-daf9b505b2b3"
Parent: "f899c3ac-cd15-431e-bac3-92a33654ecc6"
Template: "f899c3ac-cd15-431e-bac3-92a33654ecc6"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Components/Promo/Promo Media/Media Promo/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210707T230223Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3cad700f-eada-4626-bf0a-492c416ae070"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221109T044720Z
