---
ID: "d023ecb4-f427-461a-8a7f-47b26cf4a0a9"
Parent: "0c525bac-a5fe-4ccb-acd3-dc0552b7c1cc"
Template: "0c525bac-a5fe-4ccb-acd3-dc0552b7c1cc"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Forms/Forms Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{0C525BAC-A5FE-4CCB-ACD3-DC0552B7C1CC}"
- ID: "a0cb3965-8884-4c7a-8815-b6b2e5ced162"
  Hint: __Editors
  Value: "{A0C460F4-DBAE-4A5A-8F3A-C4ADFCDACEEA}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230216T192648Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3dd1d3a8-a7f4-43e1-9dbf-5a4f7245d7ea"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230802T132927Z
