---
ID: "1e98d4c8-b7b5-4a15-a609-04ab1bb3b812"
Parent: "5fabb06d-1a0c-4f91-b4f4-be57ade21198"
Template: "5fabb06d-1a0c-4f91-b4f4-be57ade21198"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Forms/Submit Actions/Send Email/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230907T095448Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b6231518-597c-4eef-9027-4d2b4872cfe9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230907T095514Z
