---
ID: "3b66d70e-94d0-45fd-8c28-4880f718bd36"
Parent: "440f9d54-60b8-40dd-96e9-3ec0a6af8cf1"
Template: "7e8b6b52-17d0-47c4-9b7c-0ebae0e7efaf"
Path: /sitecore/content/AndersenCorporation/RenewalByAndersen/Global/Products
SharedFields:
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: |
    ar|sitecore\RbA Talent Approver|pe|-item:read|pd|-item:read|
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230612T193848Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "95762db5-7f6e-41bb-8276-146cde7ffc51"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240318T090954Z
