---
ID: "f9b0bb06-f7f4-4654-ad91-2f49a0326f6f"
Parent: "8144fccf-54d0-4bd4-84b0-ef43c9f444d7"
Template: "d2923fee-da4e-49be-830c-e27764dfa269"
Path: /sitecore/content/AndersenCorporation/Enterprise Global/Enums/Comparison Tables/Section Title Fields/Big Door Options Configurations
SharedFields:
- ID: "f917c951-1f75-4d62-b14a-bc6888d7eeca"
  Hint: Value
  Value: bigDoorOptionsConfigurations
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230712T073811Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "511dff02-f7ac-4c97-8b2e-d5f41c37a5b4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230712T073815Z
