---
ID: "e8236a69-4b3c-4d03-9689-38017dcb1406"
Parent: "e1a3aa6a-1267-428e-a51f-48cc73ba96f0"
Template: "e1a3aa6a-1267-428e-a51f-48cc73ba96f0"
Path: /sitecore/templates/Feature/EnterpriseWeb/RenewalByAndersen/Forms/Fields/Appointment Calendar/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: office/32x32/calendar.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230911T090847Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fcccbc3d-03ae-46c9-920b-74c8e3a02ac8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240305T151807Z
