---
ID: "a7a895f0-033c-49f0-83b3-2e0ff6f23a4e"
Parent: "cb218dca-89ae-4002-8573-07f42ad5f856"
Template: "cb218dca-89ae-4002-8573-07f42ad5f856"
Path: /sitecore/templates/Project/AndersenCorporation/RenewalByAndersen/Common/Presentation/__Standard Values
SharedFields:
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: |
    ar|sitecore\RbA Author|pe|+item:read|!*|pd|!*|ar|sitecore\RbA Admin|pe|+item:create|+item:read|+item:rename|+item:delete|+item:write|+item:admin|pd|+item:create|+item:read|+item:rename|+item:delete|+item:write|+item:admin|
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221129T230340Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "948a620d-6bfd-43bd-92ad-951679c05d92"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230206T195154Z
