---
ID: "5a7a593f-e6ab-4c48-9ac7-522ee458065d"
Parent: "d89f1c54-45e1-4f96-8a21-5e1cd89a6b08"
Template: "d89f1c54-45e1-4f96-8a21-5e1cd89a6b08"
Path: /sitecore/templates/Foundation/EnterpriseWeb/Enterprise/FieldSets/_Item Language Fallback/__Standard Values
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230823T135341Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cb7db8d6-08dd-43b3-b772-76f5630f29f2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230823T135345Z
