---
ID: "c73a2174-232a-4dd4-bc19-2eca7e7f9c83"
Parent: "4fd88841-d725-4815-8b03-6ea12c956c18"
Template: "4fd88841-d725-4815-8b03-6ea12c956c18"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Forms/Fields/Short Text/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230216T192449Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d6ac0e49-2cb1-46d2-9277-bbda9aa2405c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d75d14d3-1a4e-47f1-a2d4-496cc1d09c0c"
      Hint: label
      Value: $name
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230801T133908Z
