---
ID: "4667ab4a-e5b2-488c-8768-70dc5322f666"
Parent: "2c03dffc-f52d-41a6-b7b0-96ede005112e"
Template: "2c03dffc-f52d-41a6-b7b0-96ede005112e"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Components/General/Cookie Consent/Cookie Consent/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230703T132318Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a90937fc-5786-4653-99c2-8e7fc451883d"
    - ID: "b93f7b61-01f9-4900-b69f-658a2f89ad00"
      Hint: acceptButtonLabel
      Value: Accept
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230706T072918Z
