---
ID: "1dfc7629-b3bd-4f90-955c-1a3b136fb32b"
Parent: "c9dbb8ea-78a9-4188-a05f-35d12b442909"
Template: "c9dbb8ea-78a9-4188-a05f-35d12b442909"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Components/General/HTML Block/HTML Block/__Standard Values
SharedFields:
- ID: "b03569b1-1534-43f2-8c83-bd064b7d782c"
  Hint: __Renderers
  Value: "{04467CFB-98D5-4EDF-BC31-961E1FBC9EBB}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230622T075511Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f9ef089a-641a-4270-9f73-e6c6f4be6ff4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230804T131251Z
