---
ID: "19c5ad14-e62f-42fc-b975-a888c107ab5c"
Parent: "aff8fb26-9492-48f7-8211-db883670d287"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Components/Product/Product Swatch/Content/productImage
SharedFields:
- ID: "1eb8ae32-e190-44a6-968d-ed904c794ebf"
  Hint: Source
  Value: "query:$siteMedia"
- ID: "21828437-ea4b-40a1-8c61-4ce60ea41db6"
  Hint: Validate Button
  Value: 
- ID: "337e20e1-999a-4eea-85ad-b58a03ae75cc"
  Hint: Quick Action Bar
  Value: 
- ID: "53c432c4-7122-4e2d-8296-db4184fd1735"
  Hint: Workflow
  Value: 
- ID: "9c903e29-650d-4af2-b9bd-526d5c14a1a5"
  Hint: Validator Bar
  Value: 
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Image
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: Product Image
  - ID: "9541e67d-ce8c-4225-803d-33f7f29f09ef"
    Hint: __Short description
    Value: AW only. For RbA the Primary Image in the Product Intro datasource should be populated.
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230427T152733Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "30a01076-ad27-4df4-b9a6-27d29fcb3b54"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dboeser
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230601T163315Z
