---
ID: "63e1923a-1441-4510-ae54-832fa08b164f"
Parent: "09b695fd-31a7-4c83-9036-cbbde23c18b8"
Template: "09b695fd-31a7-4c83-9036-cbbde23c18b8"
Path: /sitecore/templates/Foundation/EnterpriseWeb/Enterprise/FieldSets/Forms/_Field Name Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230907T101209Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ad226aa2-d7b8-429a-8695-e819175bf556"
    - ID: "ad4c0ef3-c5d0-49fc-aea4-f44e3108d489"
      Hint: fieldName
      Value: $ewNameKebab
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230907T101212Z
