---
ID: "4be156bd-ba0f-4979-b3ab-2b303730bdd6"
Parent: "8c84aed8-7c8d-4bfc-9474-e9f29ecfb545"
Template: "8c84aed8-7c8d-4bfc-9474-e9f29ecfb545"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Forms/Submit Actions/Send GTM Event/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{79C205CF-4D0C-4CA0-B056-71761739524F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230907T095159Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e003bc8c-879c-4d2b-a0f0-ab9470ad19a7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231027T061523Z
