---
ID: "3c868282-14c3-4187-932f-e5f3e70a5a63"
Parent: "8b70967e-a2ac-4f92-a099-2584e1d30523"
Template: "8b70967e-a2ac-4f92-a099-2584e1d30523"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Components/Hero/Hero Product Tabs/Hero Product Tab Item/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230217T160921Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "40d978a6-d55f-42a3-a406-3ca3afe70b91"
    - ID: "9aa36342-a88e-4a09-889c-4e740d1e5c28"
      Hint: title
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230227T173858Z
