---
ID: "24978efb-0d16-4939-aca0-57af6370f25c"
Parent: "266e8a31-e9bb-419b-816e-a9eeeba62162"
Template: "266e8a31-e9bb-419b-816e-a9eeeba62162"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Forms/Fields/Radio Button/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{4AAA5F48-2F4B-42E2-89CC-A4A92896D011}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230216T192449Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2323cbeb-780f-4128-8cbf-cb2b6b0059ae"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230822T044107Z
