---
ID: "b28c0f1d-8e91-4696-b107-7234e2bac16f"
Parent: "854a16ca-aac0-49f2-8207-fdb85dba39ac"
Template: "854a16ca-aac0-49f2-8207-fdb85dba39ac"
Path: /sitecore/templates/Feature/EnterpriseWeb/AndersenWindows/Components/General/Bazaarvoice Question Answer/Bazaarvoice Question Answer/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/list_style_numbered.png
- ID: "b03569b1-1534-43f2-8c83-bd064b7d782c"
  Hint: __Renderers
  Value: "{9340E23A-8409-4C5D-841D-4027529DF9F6}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230403T181548Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ba919c62-aa2d-40fb-bd04-07ded3721ba8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230403T182402Z
