---
ID: "3260d62d-8a45-451c-b126-3f5afd704da6"
Parent: "080bc455-3b78-4fa7-95ee-e5dea94157da"
Template: "080bc455-3b78-4fa7-95ee-e5dea94157da"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Elements/Search/Result Column/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230403T144128Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "16e125a7-e373-4587-b1a4-4bf427c3d207"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230403T144128Z
