---
ID: "c6082ca1-d501-484e-96c6-0cbfa9d82d47"
Parent: "57b24586-aebc-4cb2-b3fe-ac60a16f11e2"
Template: "57b24586-aebc-4cb2-b3fe-ac60a16f11e2"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Components/General/Page Mashup Dynamic/Result Item/__Standard Values
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230514T131958Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f6e4b14c-0b23-42c0-9672-10ffb086aa59"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230807T183308Z
