---
ID: "1bae403d-e69d-41ae-914d-f23f38d70167"
Parent: "18323d02-c884-4a7a-a74c-21eb6f87f0b6"
Template: "18323d02-c884-4a7a-a74c-21eb6f87f0b6"
Path: /sitecore/templates/Project/AndersenCorporation/AndersenWindows/Common/Partial Designs/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {77A31F8C-0D1A-4533-B9B4-C4B3EE9A6BFA}
    {FAF6B07E-455E-4B0B-AF92-E66FB99B180E}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221018T193700Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ae4e82af-8ea0-4f8f-994f-1b2f5ea355bc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221129T233614Z
