#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Our Checks
echo "Running pre-commit checks 🔎"

# Run prettier and lintng
case `uname` in
  *CYGWIN*|*MINGW*|*MSYS*)
    npm.cmd run pre-commit
  ;;
  *)
    npm run pre-commit
  ;;
esac
