---
ID: "6e105943-19e6-4eec-b72f-e91343795bee"
Parent: "9c92256d-5d4f-4e90-a46c-abfcf11212e8"
Template: "9c92256d-5d4f-4e90-a46c-abfcf11212e8"
Path: /sitecore/templates/Feature/EnterpriseWeb/RenewalByAndersen/Cards/Card Offer/__Standard Values
SharedFields:
- ID: "b03569b1-1534-43f2-8c83-bd064b7d782c"
  Hint: __Renderers
  Value: "{C1073045-B729-400E-B2EC-D89DFF1BFC6F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231222T103347Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a0b6501a-cc82-4f69-b6bf-5637f63b7a23"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231222T112806Z
