---
ID: "fc844697-4717-425d-ab21-c19f33b9a6d1"
Parent: "2cd34288-3fe6-4d29-993f-cc2140c72ddc"
Template: "2cd34288-3fe6-4d29-993f-cc2140c72ddc"
Path: /sitecore/templates/Feature/EnterpriseWeb/RenewalByAndersen/Components/Affiliates/Jobs/Job Search/Job Search/__Standard Values
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 500
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240125T140109Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5bf7fdd6-1ccb-4bf3-b0a9-a980e27ed6c2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240129T125748Z
