---
ID: "3ba979f8-a98c-4dc7-a723-5fb53be9fcc7"
Parent: "b23f556c-bb0e-42c6-8665-f626cdceb7c0"
Template: "b23f556c-bb0e-42c6-8665-f626cdceb7c0"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Components/Hero/Hero With Navigation/Hero With Navigation/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{A90F837F-CAC5-4B90-9BD0-BB062974B49D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230223T190509Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e1260814-a3e0-4da9-8639-198ef0a742a4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230223T211848Z
