---
ID: "6472fc8f-458c-4401-9b5f-cd9028d016d5"
Parent: "42b84bdf-08db-454f-9962-556994c97a16"
Template: "6f0f9b58-daec-4c55-a519-36b3207d109c"
Path: /sitecore/content/AndersenCorporation/AndersenWindows/Global/Facets/Product Options
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230323T090626Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "476aedf7-f0dc-4c50-9449-304fad10a99e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "c5c5443e-ae24-4a7e-8691-4238d55e5494"
      Hint: queryIdentifier
      Value: "product-options"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231030T191926Z
