---
ID: "f2eceb26-ae4f-46da-b29a-7f31f79807e3"
Parent: "0db2e4a5-381c-4835-8a0b-af6da82194c2"
Template: "0db2e4a5-381c-4835-8a0b-af6da82194c2"
Path: /sitecore/templates/Feature/EnterpriseWeb/Enterprise/Components/General/Helpful Links/Link/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231003T075540Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fac18a9f-5a2b-4878-9f4c-ffae7ce7327d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231003T075647Z
