name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)-alpha

trigger:
  branches:
    include:
    - develop
  paths: # TODO: Have a better way of doing this
    include:
    - azure-pipelines/id-develop.yml
    - azure-pipelines/templates/id/*
    - azure-pipelines/build/id/*
    - azure-pipelines/deployt/RolloutID.ps1

resources:
  repositories:
  - repository: enterprise-deployment
    type: git
    name: enterprise-deployment

pool:
  vmImage: windows-latest

variables:
- group: Web - Build Deploy - Global
- name: buildConfiguration
  value: Debug
- name: containerRegistry
  value: prodentwb1acr1
- name: repository
  value: enterpriseweb/enterpriseweb-id

stages:
- stage: Build
  jobs:
  - job: BuildDocker
    displayName: Build and Publish Identity Docker
    pool:
      name: Enterprise Web
    steps:
    - template: templates\id\build-docker.yml
      parameters:
        containerRegistry: $(containerRegistry)
        repository: $(repository)
        latestTag: latest-alpha
    - template: templates\publish-docker.yml
      parameters:
        containerRegistry: $(containerRegistry)
        repository: $(repository)
        latestTag: latest-alpha

- stage: Development
  dependsOn: Build
  displayName: Development
  jobs:
  - template: templates\id\deploy-docker.yml
    parameters:
      devopsEnvironment: CM-Dev
      azureSubscription: DEV_ENTWB1
      aksSubscription: AKS - ARM
      aksClusterName: AKS-Cluster1
      aksClusterResourceGroup: AKS_Cluster1a
      aksPodName: id-dev
      aksNamespace: sitecore
      sitecoreEnvironment: dev
      sitecoreIdUrl: https://id.dev.ew.andersencorp.com
      repository: $(repository)
