trigger: none

pool:
  name: Enterprise Web

stages:
- stage: Test
  jobs:
  - job: Test
    steps:
    - task: DockerInstaller@0
      displayName: Install Docker CLI
      inputs:
        dockerVersion: 20.10.24
