name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)-alpha

# trigger: none
# trigger:
#   batch: true
#   branches:
#     include:
#       - main
trigger:
- main

resources:
  repositories:
  - repository: enterprise-deployment
    type: git
    name: enterprise-deployment

pool:
  vmImage: windows-latest

variables:
- group: Web - Build Deploy - Global
- name: buildConfiguration
  value: Debug
- name: containerRegistry
  value: prodentwb1acr1
- name: repository
  value: enterpriseweb/enterpriseweb-xm1-cm
- name: VERCEL_ORG_ID # Need this defined as an environment variable for the vercel cli
  value: team_Te46li2AMhv2GDNDb4O9Tc9e

stages:
- stage: Queue
  jobs:
  - deployment: Queue
    environment: Web-Main-Queue
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Starting pipeline execution."
- stage: Build
  dependsOn: Queue
  jobs:
  - job: BuildSolution
    displayName: Build and Publish Solution
    steps:
    - template: templates\build-cm.yml
      parameters:
        buildConfiguration: $(buildConfiguration)
    - template: templates\build-iar.yml
    - template: templates\publish-solution.yml
  - job: BuildDocker
    displayName: Build and Publish Docker
    dependsOn: BuildSolution
    pool:
      name: Enterprise Web
    steps:
    - template: templates\build-docker.yml
      parameters:
        containerRegistry: $(containerRegistry)
        repository: $(repository)
        latestTag: latest-alpha
    - template: templates\publish-docker.yml
      parameters:
        containerRegistry: $(containerRegistry)
        repository: $(repository)
        latestTag: latest-alpha

- stage: DevelopmentCM
  dependsOn: Build
  displayName: Development CM
  variables:
  - group: Web - Build Deploy - Dev
  jobs:
  - template: templates\deploy-cm.yml
    parameters:
      devopsEnvironment: CM-Dev
      azureSubscription: DEV_ENTWB1
      aksSubscription: AKS - ARM
      aksClusterName: AKS-Cluster1
      aksClusterResourceGroup: AKS_Cluster1a
      aksPodName: cm-dev
      aksNamespace: sitecore
      sitecoreEnvironment: dev
      sitecoreCmUrl: https://cm.dev.ew.andersencorp.com
      sitecoreIdUrl: https://id.dev.ew.andersencorp.com
      sitecoreCliClientId: SitecoreCLIServer
      sitecoreCliClientSecret: $(SitecoreCliClientSecret)
      repository: $(repository)

- stage: DevelopmentPreviewVercelAW
  dependsOn: DevelopmentCM
  displayName: "Development Preview Vercel Andersen Windows"
  variables:
  - group: Web - Build Deploy - Dev
  - name: VERCEL_PROJECT_ID # Need this defined as an environment variable for the vercel cli
    value: prj_yQpLLPrgRFuPLN0UZzgF78wVwIjL
  jobs:
  - template: templates\deploy-vercel.yml
    parameters:
      displayName: Andersen Windows
      devopsEnvironment: CD-Preview
      vercelAliasUrl: preview-andersenwindows-dev.vercel.app
      vercelDeployToken: $(VercelDeployToken)
      vercelScope: andersen-corporation
      siteUrl: https://preview.dev.andersenwindows.com

- stage: DevelopmentPreviewVercelRbA
  dependsOn: DevelopmentCM
  displayName: "Development Preview Vercel Renewal by Andersen"
  variables:
  - group: Web - Build Deploy - Dev
  - name: VERCEL_PROJECT_ID
    value: prj_iTXB48UJUDA3NYHTZgPzpX9ak4g7
  jobs:
  - template: templates\deploy-vercel.yml
    parameters:
      displayName: Renewal By Andersen
      devopsEnvironment: CD-Preview
      vercelAliasUrl: preview-renewalbyandersen-dev.vercel.app
      vercelDeployToken: $(VercelDeployToken)
      vercelScope: andersen-corporation
      siteUrl: https://preview.dev.renewalbyandersen.com

- stage: DevelopmentVercelAW
  dependsOn:
  - DevelopmentCM
#  - DevelopmentPreviewVercelRbA
  - DevelopmentPreviewVercelAW
  displayName: "Development Vercel Andersen Windows"
  variables:
  - group: Web - Build Deploy - Dev
  - name: VERCEL_PROJECT_ID # Need this defined as an environment variable for the vercel cli
    value: prj_sgXutj2yEXZ9SEOiWAsidIa6iQ3G
  jobs:
  - template: templates\deploy-vercel.yml
    parameters:
      displayName: Andersen Windows
      devopsEnvironment: CD-Dev
      vercelAliasUrl: andersenwindows-dev.vercel.app
      vercelDeployToken: $(VercelDeployToken)
      vercelScope: andersen-corporation
      siteUrl: https://www.dev.andersenwindows.com

- stage: DevelopmentVercelRbA
  dependsOn:
  - DevelopmentCM
  - DevelopmentPreviewVercelRbA
#  - DevelopmentPreviewVercelAW
  displayName: "Development Vercel Renewal by Andersen"
  variables:
  - group: Web - Build Deploy - Dev
  - name: VERCEL_PROJECT_ID
    value: prj_nbEjEAvh75SSSkcOBDvlHzTHlU1c
  jobs:
  - template: templates\deploy-vercel.yml
    parameters:
      displayName: Renewal By Andersen
      devopsEnvironment: CD-Dev
      vercelAliasUrl: renewalbyandersen-dev.vercel.app
      vercelDeployToken: $(VercelDeployToken)
      vercelScope: andersen-corporation
      siteUrl: https://www.dev.renewalbyandersen.com

- stage: SmokeTestAW
  dependsOn:
  - DevelopmentVercelAW
  displayName: "Smoke Test Andersen Windows"
  pool:
    vmImage: ubuntu-latest
  jobs:
  - template: templates\smoke-test.yml
    parameters:
      environment: dev
